import fs from 'fs';
import YAML from 'yaml';
import { OkoConfig } from '../config';
import { registry } from './camera-registry';

const GO2RTC_CONFIG_PATH = process.env.GO2RTC_CONFIG_PATH || '/config/go2rtc/go2rtc.yaml';

/**
 * Generate go2rtc.yaml from config + camera registry.
 */
export function generateGo2rtcConfig(config: OkoConfig): void {
  const streams = registry.generateAllStreams();

  const go2rtcConfig: Record<string, unknown> = {
    api: {
      listen: ':1984',
      origin: '*',
    },
    webrtc: {
      listen: `:${config.go2rtc.webrtc_port}`,
      candidates: config.go2rtc.candidates.length > 0
        ? config.go2rtc.candidates
        : undefined,
      ice_servers: [],
    },
    ffmpeg: {
      timeout: config.playback.timeout,
      playback: config.playback.playback_input,
    },
    streams,
  };

  if (!(go2rtcConfig.webrtc as any)?.candidates) {
    delete (go2rtcConfig.webrtc as any).candidates;
  }

  const yamlStr = [
    '# Auto-generated by OKO NVR — do not edit manually',
    `# Generated at ${new Date().toISOString()}`,
    `# NVRs: ${config.nvrs.map(n => n.name).join(', ')} | Cameras: ${Object.keys(streams).length}`,
    '',
    YAML.stringify(go2rtcConfig, { lineWidth: 0 }),
  ].join('\n');

  const dir = GO2RTC_CONFIG_PATH.substring(0, GO2RTC_CONFIG_PATH.lastIndexOf('/'));
  if (dir) fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(GO2RTC_CONFIG_PATH, yamlStr, 'utf8');
  console.log(`Generated ${GO2RTC_CONFIG_PATH} with ${Object.keys(streams).length} streams`);
}
